### ISSUE TITLE
add wireless (433mhz) sensors

### ISSUE THREAD

**Issue by vtni** [dgray10/SecPi#102]
It would be great if also the codes of e.g. a wireless motion detector could be handled.

**Comment by MartinLiebl** [comment]
Hey!
New idea are always welcome :) Unfortunately we don't have the resources (time + hardware) now to implement this by ourselves. It would be cool if you could help us out by implementing this kind of sensor. We have some documentation in the wiki and I think we could help you out when you face challenges with the SecPi project.
Cheers
Martin

**Comment by zaccaro** [comment]
This could be a starting point [https://github.com/tkmaker/RaspberryPiHomeAlarm](url). "Code for setting up a Raspberry Pi based home security system using 433Mhz wireless sensors" and is in python too

**Comment by MartinLiebl** [comment]
Hey!
Sorry but we currently don't have the resources to take of this issue. If you are interested you can implement it and make a pull request against our project. We have some documentation here about how to add sensors to SecPi here: https://github.com/SecPi/SecPi/wiki/Sensors. If you have questions/problems feel free to contact us.
Cheers,
Martin
