### ISSUE TITLE
unable to connect web interfce to worker

### ISSUE THREAD

**Issue by anjushar** [dgray10/SecPi#106]
hello sir,
                i am trying to implement this secpi concept. i successfully installed manager,worker,web-interface on one raspberry pi. i am trying to make another raspberry pi  as worker. and i used this pi  (worker)  ip address in webinterface at manager in webinterface. but i am getting error, when i am trying to activate to worker at webinterface at manager (Pi). the error i am getting is "error activating away! No connection to queue server!". can you guide me in solving this problem.

**Comment by MartinLiebl** [comment]
Hey!
Sorry for the late reply,  did you follow these steps: https://github.com/SecPi/SecPi/wiki/Worker-Setup ? And you see this error in the webinterface right?

**Comment by anjushar** [comment]
hai sir, I followed as given in above secpi link. where i am trying to install setup for manager and worker and webinterface in one raspberry pi..web. I used pi board ip address(192.168.1.100) during installation and worked fine for first time. For next time, since the ip address (192.168.1.112)of pi board changed, i am getting error while trying to activate setup in webinterface ui, poping a comment "error activating away! No connection to queue server". i checked all config.json files and editted to new address. Even though error is same.
i tried to check status of rabbitmq server.it shows already server with name rabbit is running.How to solve this problem?

**Comment by anjushar** [comment]
root@raspberrypi:/home/pi/Downloads/SecPi-master# /etc/init.d/secpi-manager status
● secpi-manager.service - SecPi Manager
   Loaded: loaded (/etc/systemd/system/secpi-manager.service; enabled)
   Active: active (running) since Wed 2017-10-18 05:35:08 UTC; 14min ago
 Main PID: 12700 (python)
   CGroup: /system.slice/secpi-manager.service
           └─12700 python /opt/secpi/manager/manager.py /opt/secpi

Oct 18 05:45:11 raspberrypi manager.py[12700]: 2017-10-18 05:45:11,825 [ERROR] Wasn't able to connect to rabbitmq service: Connection to 192.168.1...n refused
Oct 18 05:45:41 raspberrypi manager.py[12700]: 2017-10-18 05:45:41,864 [ERROR] Wasn't able to connect to rabbitmq service: Connection to 192.168.1...n refused
Oct 18 05:46:11 raspberrypi manager.py[12700]: 2017-10-18 05:46:11,886 [ERROR] Wasn't able to connect to rabbitmq service: Connection to 192.168.1...n refused
Oct 18 05:46:41 raspberrypi manager.py[12700]: 2017-10-18 05:46:41,925 [ERROR] Wasn't able to connect to rabbitmq service: Connection to 192.168.1...n refused
Oct 18 05:47:11 raspberrypi manager.py[12700]: 2017-10-18 05:47:11,965 [ERROR] Wasn't able to connect to rabbitmq service: Connection to 192.168.1...n refused
Oct 18 05:47:42 raspberrypi manager.py[12700]: 2017-10-18 05:47:42,012 [ERROR] Wasn't able to connect to rabbitmq service: Connection to 192.168.1...n refused
Oct 18 05:48:12 raspberrypi manager.py[12700]: 2017-10-18 05:48:12,047 [ERROR] Wasn't able to connect to rabbitmq service: Connection to 192.168.1...n refused
Oct 18 05:48:42 raspberrypi manager.py[12700]: 2017-10-18 05:48:42,097 [ERROR] Wasn't able to connect to rabbitmq service: Connection to 192.168.1...n refused
Oct 18 05:49:12 raspberrypi manager.py[12700]: 2017-10-18 05:49:12,144 [ERROR] Wasn't able to connect to rabbitmq service: Connection to 192.168.1...n refused
Oct 18 05:49:42 raspberrypi manager.py[12700]: 2017-10-18 05:49:42,192 [ERROR] Wasn't able to connect to rabbitmq service: Connection to 192.168.1...n refused
Hint: Some lines were ellipsized, use -l to show in full.
root@raspberrypi:/home/pi/Downloads/SecPi-master# 

hai sir, above mentioned is getting as error. could you solve it.

**Comment by MartinLiebl** [comment]
Ok, so because you changed the IP of the pi you have to change the IP address in all the configuration files. It seems you did that for the Secpi configuration files, but you also have to change the configuration of the rabbitmq service to listen on the new IP. On debian* the file is located at /etc/rabbitmq/. Afterwards restart all the services (or the whole system).

(*) https://www.rabbitmq.com/configure.html#config-location

**Comment by anjushar** [comment]
hai sir, below is what present in   nano /etc/rabbitmq/rabbitmq.config   .In this where should be the change related to new ip.

[
  {rabbit, [
     {ssl_handshake_timeout, 10000},
     {ssl_listeners, [5671]},
     {ssl_options, [{cacertfile,"/opt/secpi/certs/ca/cacert.pem"},
                    {certfile,"/opt/secpi/certs/mq-server.secpi.local.cert.pem"$
                    {keyfile,"/opt/secpi/certs/mq-server.secpi.local.key.pem"},
                    {verify,verify_peer},
                    {fail_if_no_peer_cert,false}]}
   ]}
].

**Comment by MartinLiebl** [comment]
Sorry I confused something, do you have the correct IP address in the following configuration files?
/opt/secpi/manager/config.json
/opt/secpi/webinterface/config.json
/opt/secpi/worker/config.json

**Comment by MartinLiebl** [comment]
Any success with the mentioned configuration files?

**Comment by anjushar** [comment]
hai sir, i changed ip address in all config.json files  , with my raspberry pi, ip address but same error.i was not enabled to active setup in web ui.

i formatted os in raspberry pi and once again installed noobs OS, and installed steps as given in secpi project. it is working now. but when ip address of pi changes, i am facing the same problem.
can you suggest me , the exact changes to be done, and in what files to be done, when an ip address changes for a raspberry pi which as noobs os. 

besides this, can you give some more information about settings in notifier class when sender and receiver has gmail account.

Thanks in advance.

**Comment by MartinLiebl** [comment]
So the problem is that the IP address changes because our software doesn't deal with this. I see two things you could do to resolve this issue:
1. Configure a static IP address on your Pi so that it will always have the same.
2. On the router where your Pi connects to you could configure DHCP to always give the same IP address to the MAC address of your Pi.

Hope that helps!
