### ISSUE TITLE
Installation is not working

### ISSUE THREAD

**Issue by sebska** [dgray10/SecPi#110]
Hallo,

ich habe Euer Projekt gefunden und würde es gerne bei mir Zuhaus ausprobieren und (wenn ich einarbeite) auch noch Status-LED oder einen Schlüsselschalter zum "schärfen" zum Code hinzufügen.
Ich habe noch nicht oft mit Unix-Systemen gearbeitet, ich schätze mich aber auch nicht als DAU ein.

Ich hatte noch einen PI B+ im Schrank, den habe ich mit NOOBS auf einer 8GB-Karte gestartet, das Dateisystem über das Config-Menü erweitert und ein System-Upgrade gemacht. Alles Headless, ich komme über ssh an alles heran (Terminmalfenster und Filesystem).
Nach dem Upgrade habe ich die Dateien hinüberkopiert (ins Home Verzeichnis) und wie im WIKI beschrieben die Installation (mit Sudo) gestartet.

In der Abarbeitung des Scriptes nach der Eingabe der Parameter kommen Fehlermeldungen:

Creating htdigest file...
./install.sh: line 351: webinterface/create_htdigest.sh: Permission denied
Copying startup scripts...
Error: unable to connect to node rabbit@SecPi1: nodedown

DIAGNOSTICS
===========

attempted to contact: [rabbit@SecPi1]

rabbit@SecPi1:
  * connected to epmd (port 4369) on SecPi1
  * epmd reports: node 'rabbit' not running at all
                  no other nodes on SecPi1
  * suggestion: start the node

current node details:
- node name: 'rabbitmq-cli-43@SecPi1'
- home dir: /var/lib/rabbitmq
- cookie hash: Qmy1U6PZdkQCmYi/ddLdgQ==

Error adding RabbitMQ user!
Error: unable to connect to node rabbit@SecPi1: nodedown

DIAGNOSTICS
===========

attempted to contact: [rabbit@SecPi1]

rabbit@SecPi1:
  * connected to epmd (port 4369) on SecPi1
  * epmd reports: node 'rabbit' not running at all
                  no other nodes on SecPi1
  * suggestion: start the node

current node details:
- node name: 'rabbitmq-cli-70@SecPi1'
- home dir: /var/lib/rabbitmq
- cookie hash: Qmy1U6PZdkQCmYi/ddLdgQ==

Error setting RabbitMQ permissions!
 
In der Folge kann ich die Dienste starten, aber ich komme nicht auf die Web-Seite und in den Logs vom Manager und dem Web-Interface sind viele Einträge bezüglich des rabbitmq zu sehen.

Manager

2017-11-17 10:47:56,076 [INFO] Initializing manager
2017-11-17 10:47:56,878 [ERROR] Wasn't able to connect to rabbitmq service: Connection to 192.168.6.70:5671 failed: [Errno 111] Connection refused
2017-11-17 10:48:26,947 [ERROR] Wasn't able to connect to rabbitmq service: Connection to 192.168.6.70:5671 failed: [Errno 111] Connection refused
2017-11-17 10:48:57,017 [ERROR] Wasn't able to connect to rabbitmq service: Connection to 192.168.6.70:5671 failed: [Errno 111] Connection refused
2017-11-17 10:49:27,085 [ERROR] Wasn't able to connect to rabbitmq service: Connection to 192.168.6.70:5671 failed: [Errno 111] Connection refused
2017-11-17 10:51:48,140 [INFO] Initializing manager
2017-11-17 10:51:49,455 [ERROR] Wasn't able to connect to rabbitmq service: Connection to 192.168.6.70:5671 failed: [Errno 111] Connection refused
2017-11-17 10:52:19,506 [ERROR] Wasn't able to connect to rabbitmq service: Connection to 192.168.6.70:5671 failed: [Errno 111] Connection refused

Webinterface
17/Nov/2017:10:48:18]  Initializing Webserver
[17/Nov/2017:10:48:18]  Trying to connect to rabbitmq service...
[17/Nov/2017:10:48:19]  Error connecting to Queue! Connection to 192.168.6.70:5671 failed: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/opt/secpi/webinterface/main.py", line 114, in connect
    self.connection = pika.BlockingConnection(parameters=parameters)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 374, in __init__
    self._process_io_for_connection_setup()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 414, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 468, in _flush_output
    raise exceptions.ConnectionClosed(maybe_exception)
ConnectionClosed: Connection to 192.168.6.70:5671 failed: [Errno 111] Connection refused
[17/Nov/2017:10:48:49]  Trying to connect to rabbitmq service...
[17/Nov/2017:10:48:49]  Error connecting to Queue! Connection to 192.168.6.70:5671 failed: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/opt/secpi/webinterface/main.py", line 114, in connect
    self.connection = pika.BlockingConnection(parameters=parameters)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 374, in __init__
    self._process_io_for_connection_setup()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 414, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 468, in _flush_output
    raise exceptions.ConnectionClosed(maybe_exception)
ConnectionClosed: Connection to 192.168.6.70:5671 failed: [Errno 111] Connection refused

Was mache ich falsch?

Beste Grüße und vielen Dank für das (bisher nur theoretisch) gute Projekt)

Sebastian

**Comment by sebska** [comment]
Oh, was it alright to post in German?

**Comment by phwoelfel** [comment]
Hallo!
Deutsch ist kein Problem ;-)

Es schaut so aus, als würd der RabbitMQ Dienst nicht starten. Könntest du mal unter /var/log/rabbitmq in den Logs nach Fehlern suchen?


Zum Fehler:
./install.sh: line 351: webinterface/create_htdigest.sh: Permission denied

Damit wird das User File für die Weboberfläche angelegt. Parameter für das Skript sind wenn ichs richtig im Kopf hab Dateiname, User und Passwort. Dateiname ist .htdigest (im webinterface Ordner).


LG Philip

**Comment by sebska** [comment]
Hallo Philip,

Ich habe die SD noch mal platt gemacht und von vorne begonnen.
und wieder: der Rabbitmq läuft nicht richtig, so sehe ich das mit meinen kleinen Unixwissen auch.

das Logfile aus  /var/log/rabbitmq häne ich mal an.
[rabbit@SecPi1.log](https://github.com/SecPi/SecPi/files/1521462/rabbit.SecPi1.log)

Heute (1.12.) habe ich den server als root mit `service rabbitmq-server start &` versucht zu starten. es scheint auch funktioniert zu haben:

root@SecPi1:~# service rabbitmq-server start &
[1] 16122
root@SecPi1:~# service rabbitmq-server start &[K
[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[12Prabbitmqctl[C[C[C[C[C[Ctus
Status of node rabbit@SecPi1 ...
[{pid,16032},
 {running_applications,[{rabbit_common,[],"3.6.6"},
                        {os_mon,"CPO  CXC 138 46","2.4.1"},
                        {xmerl,"XML parser","1.3.12"},
                        {sasl,"SASL  CXC 138 11","3.0.2"},
                        {stdlib,"ERTS  CXC 138 10","3.2"},
                        {kernel,"ERTS  CXC 138 10","5.1.1"}]},
 {os,{unix,linux}},
 {erlang_version,"Erlang/OTP 19 [erts-8.2.1] [source] [async-threads:64] [kernel-poll:true]\n"},
 {memory,[{total,22247336},
          {connection_readers,0},
          {connection_writers,0},
          {connection_channels,0},
          {connection_other,0},
          {queue_procs,0},
          {queue_slave_procs,0},
          {plugins,0},
          {other_proc,12278960},
          {mnesia,0},
          {mgmt_db,0},
          {msg_index,0},
          {other_ets,367068},
          {binary,151584},
          {code,6342744},
          {atom,391509},
          {other_system,2715471}]},
 {alarms,[]},
 {listeners,[]},
 {processes,[{limit,1048576},{used,64}]},
 {run_queue,1},
 {uptime,47},
 {kernel,{net_ticktime,60}}]

jedoch auf ein `rabbitmq status` kommt

root@SecPi1:/home/pi/secpi# rabbitmqctl status
Status of node rabbit@SecPi1 ...
Error: unable to connect to node rabbit@SecPi1: nodedown

DIAGNOSTICS
===========

attempted to contact: [rabbit@SecPi1]

rabbit@SecPi1:
  * connected to epmd (port 4369) on SecPi1
  * epmd reports: node 'rabbit' not running at all
                  no other nodes on SecPi1
  * suggestion: start the node

current node details:
- node name: 'rabbitmq-cli-25@SecPi1'
- home dir: /var/lib/rabbitmq
- cookie hash: 6l+0Z/Vi680mUk1bTCRf1Q==

root@SecPi1:/home/pi/secpi#





Bei der zweiten Installation wurde der zweite Fehler nicht wiederholt, weiss der Teufel, was ich da falsch gemacht hatte.


Beste Grüße

Sebastian

**Comment by sebska** [comment]
OK,

ich scheine den rabbitmq Beine gemacht zu haben.


pi@SecPi1:/ $ sudo rabbitmqctl status
Status of node rabbit@SecPi1 ...
[{pid,2662},
 {running_applications,[{rabbit,"RabbitMQ","3.6.6"},
                        {ssl,"Erlang/OTP SSL application","8.1"},
                        {public_key,"Public key infrastructure","1.3"},
                        {crypto,"CRYPTO","3.7.2"},
                        {asn1,"The Erlang ASN1 compiler version 4.0.4",
                              "4.0.4"},
                        {ranch,"Socket acceptor pool for TCP protocols.",
                               "1.2.1"},
                        {mnesia,"MNESIA  CXC 138 12","4.14.2"},
                        {rabbit_common,[],"3.6.6"},
                        {os_mon,"CPO  CXC 138 46","2.4.1"},
                        {xmerl,"XML parser","1.3.12"},
                        {sasl,"SASL  CXC 138 11","3.0.2"},
                        {stdlib,"ERTS  CXC 138 10","3.2"},
                        {kernel,"ERTS  CXC 138 10","5.1.1"}]},
 {os,{unix,linux}},
 {erlang_version,"Erlang/OTP 19 [erts-8.2.1] [source] [async-threads:64] [kernel-poll:true]\n"},
 {memory,[{total,25610424},
          {connection_readers,0},
          {connection_writers,0},
          {connection_channels,0},
          {connection_other,0},
          {queue_procs,1348},
          {queue_slave_procs,0},
          {plugins,0},
          {other_proc,11307248},
          {mnesia,30084},
          {mgmt_db,0},
          {msg_index,25352},
          {other_ets,491616},
          {binary,21992},
          {code,9680500},
          {atom,577013},
          {other_system,3475271}]},
 {alarms,[]},
 {listeners,[{clustering,25672,"::"},{amqp,5672,"::"},{'amqp/ssl',5671,"::"}]},
 {vm_memory_high_watermark,0.4},
 {vm_memory_limit,182080307},
 {disk_free_limit,50000000},
 {disk_free,9773641728},
 {file_descriptors,[{total_limit,924},
                    {total_used,2},
                    {sockets_limit,829},
                    {sockets_used,0}]},
 {processes,[{limit,1048576},{used,152}]},
 {run_queue,0},
 {uptime,211},
 {kernel,{net_ticktime,60}}]
pi@SecPi1:/ $
pi@SecPi1:/ $
pi@SecPi1:/ $
pi@SecPi1:/ $
pi@SecPi1:/ $ sudo /etc/init.d/secpi-manager start
[ ok ] Starting secpi-manager (via systemctl): secpi-manager.service.
pi@SecPi1:/ $ sudo /etc/init.d/secpi-webinterface start
[ ok ] Starting secpi-webinterface (via systemctl): secpi-webinterface.service.
pi@SecPi1:/ $ sudo /etc/init.d/secpi-manager status
â secpi-manager.service - SecPi Manager
   Loaded: loaded (/etc/systemd/system/secpi-manager.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2017-12-08 11:53:21 CET; 1s ago
 Main PID: 3154 (python)
   CGroup: /system.slice/secpi-manager.service
           ââ3154 python /opt/secpi/manager/manager.py /opt/secpi

Dec 08 11:53:21 SecPi1 systemd[1]: Started SecPi Manager.
pi@SecPi1:/ $


Ich habe noch erlang installiert. 

Und ich muss prüfen, warum der rabbitmq nach einem reboot nicht automatisch startet.

Aber jetzt komme ich nicht auf das Webinterface vom SecPi....

**Comment by sebska** [comment]
Welche Pakete auf dem Pi sind für die Web-Seite da?
Ich habe mein Pi mal vom Netzwerk aus gescannt, es sind keine http / https -Ports offen.
Wie kann ich den Status der Web-Seite auf dem Pi prüfen?

**Comment by MartinLiebl** [comment]
Hey!
Normalerweise läuft das Webinterface auf Port 8443 (siehe https://github.com/SecPi/SecPi/wiki/Configuration), müsste dann bei einem Scan als offen erscheinen bzw. kannst dus am Pi via `netstat` prüfen. Logs werden nach `/var/log/secpi` geschrieben, und dort sollte es auch etwas für das webinterface geben.

**Comment by sebska** [comment]
Hallo!

also der Port ist nicht offen. Anbei das Log für das Webinterface.
[webinterface.log](https://github.com/SecPi/SecPi/files/1605802/webinterface.log)

Ich überlege echt, das ganze nochmal aufzusetzen. So tief reichen dann meine Kentnisse nicht, hier im (wie ich es fühle) Nebel herumzustochern.

Ich habe einen PI B+. Sollte ich da die neuste Rasbian-version nehmen? Bei der Installation gleich mit "sudo su-" arbeiten? Ist Eure Installationsanleitung noch aktuell? Ich hatte z.B. noch Erlang installiert...

**Comment by MartinLiebl** [comment]
Servus!
Ich hab jetzt mal bei mir ein bisschen rumprobiert und eine mögliche Fehlerquelle gefunden... bei mir fehlten jetzt bei einer Neuinstallation die Leseberechtigungen für die Zertifikate und deswegen hat die Verbindung nicht geklappt. Probier mal bitte unter `/opt/secpi/certs` den Befehl `chmod +r *` und unter `/opt/secpi/certs/ca/` den Befehl `chmod +r cacert.pem` auszuführen. Dann neustarten und schauen obs funktioniert.
Installationsanleitung ist aktuell. Funktionieren tuts am besten mit dem root User, mit anderen User kanns Probleme geben wegen Berechtigungen.

**Comment by MartinLiebl** [comment]
Ich hab jetzt einen Fehler gefunden und behoben. Falls du nochmal frisch starten möchtest nimm einfach den neuesten Release. Falls du aber 1.0.3 noch hast kannst du probieren das Problem selbst mit `chmod +r /opt/secpi/certs/*` und einem Neustart zu lösen. Sollte das nicht die Lösung sein kannst du noch probieren die ganze Installation als root User zu machen. Wenn das nicht klappen sollte können wir gern auch mal skypen und uns die Sache gemeinsam ansehen.

Liebe Grüße

Martin

**Comment by sebska** [comment]
Hallo Martin und Philip,

nach Neuinstallation läuft jetzt der Manager, das Webinterface und der Worker. Weiß der Teufel, was vorher schief gelaufen ist.

Meine Testconfig:
1) einen Worker angelegt mit der selben IP wie der Manager
2) ein Setup angelegt (Name: Garage_Scharf)
3) eine Zone angelegt
4) einen Sensor TCPPortlistener angelegt (IP wie secpi, Port 8080)
Der Sensor hat die Zone und den Worker von den oben angelegten.

5) Setup und Zone miteinander verknüpft

Wenn ich jetzt mein Setup aktivieren will, so kommt die Fehlermeldung (rechts unten in einem roten "popup": Error activating Garage_Scharf! No connection to queue server!

Aus den Logs sind keine Fehler ersichtlich. Wo hängt es jetzt schon wieder?

Noch eine Frage: sehe ich es richtig, das ich auch Magnetkontakte an den GPIO anschließen kann? Also die 3,3V aus dem Pi über einen Magnetkontakt gegen einen GPIO? Wenn 0V, dann alles OK, wenn +3,3V am GPIO, dann Alarm?


 Beste Grüße

Sebastian

**Comment by MartinLiebl** [comment]
Hey Sebastian!

Die Fehlermeldung deutet immer noch auf ein Verbindungsproblem zum RabbitMQ Service hin. Ich nehme an du hast Version 1.0.4 installiert oder die von mir genannten Schritte durchgeführt?
Wenn du magst könnten wir mal gemeinsam skypen und ich schau mir das Problem Live an.

Bezüglich Magnetkontakt: Ja es gibt Sensoren die man per GPIO anschließen kann, aber ich hab mich damit noch nicht beschäftigt. Kann dir jetzt nich garantiert sagen ob das direkt mit unserem GPIO Sensor funktioniert, oder ob man da eine andere Implementierung schreiben müsste.

Liebe Grüße

Martin

**Comment by sebska** [comment]
Hallo Martin,

das mit dem Skypen ist nicht so einfach. Ich schaffe es (durch den Familienbetrieb) nicht, zu bestimmten Zeitpunkten an dem Projekt zu arbeiten. Meist sind es "nur" immer wieder mal 10 Minuten zwischendurch, irgendwann....

Ich versuche gerade die Struktur vom Secpi zu durchschauen. 
Wo kann ich den Log-Level einstellen? Es scheint im Code ja verschieden zu geben. (z.B. logging.debug, logging.exception, logging.info, ......)
In den Secpi-Logs würde ich gerne detaillierter Lesen, was passiert. Ich glaube, das sich irgendwas zwischen Manager und Worker verklemmt hat. Nach einem Reboot taucht im Log des Workers nämlich auf:

2018-01-16 19:31:00,966 [INFO] Initializing worker 
2018-01-16 19:32:01,081 [INFO] Trying to establish a connection to the manager 
2018-01-16 19:32:01,568 [INFO] Connection to manager established 
2018-01-16 19:32:01,718 [INFO] Setting up sensors and actions 
2018-01-16 19:32:01,726 [INFO] No sensors configured 
2018-01-16 19:32:01,733 [INFO] No actions configured 
2018-01-16 19:32:01,736 [INFO] Setup done!

Obwohl ich Sensoren für den Worker eingerichtet habe.
-------------------------------------------------------
Die Installation habe ich so gemacht:
- das aktuelle Raspian heruntergeladen und mit etcher auf die 16GB-SD geschrieben.
-auf der SD im root-Verzeichnis eine leere Datei mit dem Namen ssh angelegt (für den ssh-Zugriff)
-den Pi gebooted, mit ssh verbunden und dann:
login mit defaultwerten: user <pi>
passwd (zum ändern des defaultpw)
sudo su -  (root erlangen)
apt-get update
apt-get upgrade
apt-get clean
apt-get install git
git clone https://github.com/dgray10/SecPi.git /home/pi/secpi
apt-get update
apt-get install python-pip python-dev python-openssl
apt-get install rabbitmq-server
cd /home/pi/secpi
./install.sh
reboot
service rabbitmq-server start
/etc/init.d/secpi-manager start
/etc/init.d/secpi-webinterface start

Den Rabbitmq starte ich durch einen Eintrag in /etc/rc.local
Dort habe ich die Zeile "service rabbitmq-server start" eingefügt.
---------------------------------------------------------
In Python möchte ich mich auch noch einarbeiten, um zu diesem Projekt beizutragen. Mir schwebten noch LED-Anzeigen über einen GPIO-Output vor, je nach aktiv/deaktiv eines Setups. Auch einen GPIO-Taster für einen Schlüsselschalter (z.B. an der Tür) zum akivieren/deakivieren eines Setups. Dann kann man die Anlage auch ohne Web-Interface bedienen. Gibt es soetwas wie einer erweiterte Dokumentation? Auf der Seite https://github.com/SecPi/SecPi/wiki/Installation-SecPi sind schon einige Hinweise gegeben.

Beste Grüße

Sebastian

**Comment by MartinLiebl** [comment]
Hey!
Sorry für die späte Antwort. In der logging.conf kannst du das Loglevel ändern. Unter [handler_file] bei level statt INFO --> DEBUG nehmen (Prozesse müssen dann neugestartet werden).
Im Normalfall brauchst du RabbitMQ und die SecPi Services nicht manuell starten, die machen das nach einem Reboot nach der Installation automatisch.
RabbitMQ hat bei uns Probleme gemacht wenn wir die SD Karte nicht expanded haben, siehe:
* https://github.com/SecPi/SecPi/wiki/Installation-Requirements
* https://elinux.org/RPi_raspi-config#expand_rootfs_-_Expand_root_partition_to_fill_SD_card
Das geht über das raspi-config tool.

Connection zum Manager hat aber laut deinem Logoutput funktioniert. Der Worker bekommt die Config aber erst wenn du das Setup aktivierst, also vielleicht liegts daran?

Mehr Doku als im Wiki haben wir im Moment nicht, sind aber für Fragen immer da. Erweiterungen sind natürlich auch gerne gesehen!

Liebe Grüße

Martin

**Comment by MartinLiebl** [comment]
Couldn't reproduce issue.
