### ISSUE TITLE
'{{DEAMONUSER}}' not found on start service

### ISSUE THREAD

**Issue by pengocha** [dgray10/SecPi#112]
Hi, i installed the software with git clone command and followed the wiki guide, When i come to the first start part i see that i should have 3 startup scripts in my /etc/init.d folder. With my install those are not there but i found them in the folder /SecPi/scripts/. I get an error saying 
> ' [....] Starting system secpi-webinterface daemon:start-stop-daemon: user '{{DEAMONUSER}}' not found, failed!' 
when i try to start them.

This happens with all 3 scripts. Anybody knows how to fix this? Thx.

**Comment by MartinLiebl** [comment]
Hey!
Just to be sure, so you followed the guide here: https://github.com/SecPi/SecPi/wiki/Installation-Requirements and here: https://github.com/SecPi/SecPi/wiki/Installation-SecPi? 
Usually the scripts will be copied to /etc/init.d/ during the execution of the install.sh script.

**Comment by MartinLiebl** [comment]
No further info about the issue
