### ISSUE TITLE
error activating <setup> no connection to queue server

### ISSUE THREAD

**Issue by JoSubel** [dgray10/SecPi#113]
hello sir,
i am trying to implement this secpi concept. i successfully installed manager,worker,web-interface on one raspberry pi.
After setting up the SecPi I try to activate an setup. Then I get the error message "error activating setup no connection to queue server".

Can you please explain what the message means and how to solve the problem?

Kind regards,
Joop

**Comment by MartinLiebl** [comment]
Hey!
I noticed that there might be a problem with permissions. Please go to `/opt/secpi/certs` and run `chmod +r *` and afterwards go to `/opt/secpi/certs/ca` and run `chmod +r cacert.pem`. Afterwards restart the system and see if that helps.

Cheers
Martin

**Comment by JoSubel** [comment]
Martin,

Thank you. It works now.

Kind regards,
Joop
