### ISSUE TITLE
Installing Problem

### ISSUE THREAD

**Issue by Cyber-Barista** [dgray10/SecPi#115]
Hello everybody,

I am new to GitHub and Raspberry and if it is wrong to post here post please move accordingly. Thank you. :)

My problem is this.
When installing with `bash install.sh` the error message 
`Installing python requirements ...
Traceback (most recent call last):
File "/ usr / bin / pip", line 9, in <module>
from pip import main
ImportError: can not import name main
Error installing requirements! `

Pip is installed in the version (9.0.1-2 + rpt2).

I do not know anymore.
Best thanks in advance.

**Comment by MartinLiebl** [comment]
Hey,

could you please try and install another python library with pip and see if it works?
