### ISSUE TITLE
Configuration page not available

### ISSUE THREAD

**Issue by Minazerac** [dgray10/SecPi#116]
Hello I followed the installation process without any problem. I started the services of the manager and the webinterface both on active(running) status but I am unable to connect to https://192.168.1.10/8443.The web page is not there. This is on a fresh installed raspbian 10. Any insight?

**Comment by phwoelfel** [comment]
Hey!

You have to use https://192.168.1.10:8443 ;) 
(notice the : instead of a / )

**Comment by Minazerac** [comment]
Sorry the typo is on the post :).. I use https://192.168.1.10:8443 without any luck...

**Comment by MartinLiebl** [comment]
Hey,
sorry for the late reply, did you manage to get on the webpage? Can you verify that the webui process is running?
