### ISSUE TITLE
remove project_path config

### ISSUE THREAD

**Issue by phwoelfel** [dgray10/SecPi#18]
Remove the project_path config variable because it will be overridden when the config is pushed to the workers.
Maybe get the current directory or give it as parameter via the startup skript?

**Comment by MartinLiebl** [comment]
When trying to start manager:
root@dgray10:~/SecPi# ./startup.sh manager
Traceback (most recent call last):
  File "manager.py", line 266, in <module>
    mg = Manager()
  File "manager.py", line 23, in **init**
    db.connect()
  File "/root/SecPi/tools/db/database.py", line 14, in connect
    engine = create_engine("sqlite:///%s/data.db"%PROJECT_PATH, echo = False) # echo = true aktiviert debug logging
NameError: global name 'PROJECT_PATH' is not defined
Exception AttributeError: "Manager instance has no attribute 'connection'" in <bound method Manager.__del__ of <__main__.Manager instance at 0xbd5620>> ignored

**Comment by phwoelfel** [comment]
problem with db in manager fixed in dc5f75e7c4395d5607fb5e45eb7e8d6f31d0181e

**Comment by phwoelfel** [comment]
is now passed to the python scripts via the startup skripts

**Comment by adilshehzad786** [comment]
> When trying to start manager:
> root@dgray10:~/SecPi# ./startup.sh manager
> Traceback (most recent call last):
> File "manager.py", line 266, in
> mg = Manager()
> File "manager.py", line 23, in **init**
> db.connect()
> File "/root/SecPi/tools/db/database.py", line 14, in connect
> engine = create_engine("sqlite:///%s/data.db"%PROJECT_PATH, echo = False) # echo = true aktiviert debug logging
> NameError: global name 'PROJECT_PATH' is not defined
> Exception AttributeError: "Manager instance has no attribute 'connection'" in <bound method Manager.**del** of <**main**.Manager instance at 0xbd5620>> ignored

Dear Please Change PROJECT_PATH TO BASE_DIR
