### ISSUE TITLE
Finish mailer implementation

### ISSUE THREAD

**Issue by MartinLiebl** [dgray10/SecPi#26]
- [x] Mail via SSL/TLS
- [x] Mail without SSL/TLS
- [x] Mail without Authentication

**Comment by phwoelfel** [comment]
Currently available methods:
- With Authentication
  - No SSL
  - STARTTLS
  - SSL
- Without Authentication
  - No SSL
  - STARTTLS
  - SSL

Implemented but **NOT** tested!

**Comment by phwoelfel** [comment]
tested, works as expected
