### ISSUE TITLE
Implement Data Queue

### ISSUE THREAD

**Issue by phwoelfel** [dgray10/SecPi#4]
Implement the data queue on manager and worker.
- [x] Worker
- create/clear folder for new action execution
- after all actions finished send data from folder to manager
- send finished message to manager
- [x] Manager
- wait for finished message for data queue
- zip contents of folder from data received for a alarm
- send contents via email etc.

**Comment by MartinLiebl** [comment]
worker part is almost done, only finished message is missing

**Comment by MartinLiebl** [comment]
Implementation was done without the finished message. The worker now sends the data which was generated by its actions. If there is no data an empty message is sent.
The manager stores the data it receives and increases a counter (also if the message is empty).
