### ISSUE TITLE
Show alarm data on webinterface

### ISSUE THREAD

**Issue by phwoelfel** [dgray10/SecPi#48]
Show contents of alarm folder on webpage. Extract zip files when user selects alarm.

**Comment by phwoelfel** [comment]
TODO: exception handling (see #8)

**Comment by linuxsenstms** [comment]
Hi, I don't know if its the right place/issue, but everything seems to be fine after installation SecPi vers. 1.0.4 but there are no pictures/jpg in folder "alarm_data"! PIRSensor works fine and camera also works fine by testing via python-scripts.  Thanks in advance,
kind regards, Didi
