### ISSUE TITLE
add holddown timeout between alarms

### ISSUE THREAD

**Issue by phwoelfel** [dgray10/SecPi#5]
In the manager add a holddown timer to not trigger the same alarm multiple times.

**Comment by phwoelfel** [comment]
Also "group" alarms that occur at the same time (about 60 seconds?) together

**Comment by MartinLiebl** [comment]
TODO: test if holddown works as expected

**Comment by MartinLiebl** [comment]
Current implementation works as expected:
If there is an alarm during holddown state there are no further actions executed but the alarm message is logged and stored in the database. The message shows, that the second/third/... alarm was during the holddown state.
