### ISSUE TITLE
exception handling

### ISSUE THREAD

**Issue by phwoelfel** [dgray10/SecPi#8]
Implement exception handling
- [x] both
  - [x] connection to RabbitMQ server
- [x] Manager
  - [x] connection to db
- [x] Worker
  - [x] config file writing
  - [x] config file validation
  - [x] class_for_name
  - [x] add gpio event detect (see #10)
  - [x] exception in action

**Comment by phwoelfel** [comment]
Also check access to config variables:

```
Traceback (most recent call last):
  File "manager.py", line 257, in <module>
    mg = Manager()
  File "manager.py", line 71, in __init__
    for notifier in config.get("notifications"):
  File "/Users/philip/fhstp/8_sem/99_alarmpi/dev/tools/config.py", line 24, in get
    return conf[key]
KeyError: 'notifications'
```

--> create method to get config variables with exception handling (and default values? like get('key', 'default') )

**Comment by phwoelfel** [comment]
class_for_name error handling in 364ff2904c261e7aa979d2367229907b3b838a69

**Comment by phwoelfel** [comment]
add gpio event detect: handled with action/sensor setup
config file writing and validation
fixed in d83f959d014c784a746795ffc51d7dfa385f4c15

**Comment by MartinLiebl** [comment]
- [x] got_data in manager:224
- [x] got_alarm in manager:270

**Comment by phwoelfel** [comment]
action exception handling will be dealt with in #63
