### ISSUE TITLE
How to get action repeated when a new alarm is detected

### ISSUE THREAD

**Issue by githubfrance** [dgray10/SecPi#90]
Hi Martin Hi Philip
Thank you for all this nice work.

II am working on an enhancement of the worker. I am using an accelerometer to detect shocks (vibration) for example when someone wants to brake a windows or a door.
All the stuff is working fine BUT, when the sensor sends an alarm, the action is only working once.
I tested Buzzer and Speaker who reacts identically, Action only after 3 minutes.
What should I do to have an action EACH time (or after X seconds)  an alarm raised up ?
BR
Patrick

**Comment by phwoelfel** [comment]
Hey!
This sounds like a really cool enhancment! :)
Generally Actions should be started each time an alarm is recieved, but we have added an holddown timer to prevent the alarms from occuring too often in a short period of time.
This is configured on the manager (see: https://github.com/SecPi/SecPi/blob/master/manager/manager.py#L64). You can simply add

```
"holddown_timer": 10
```

to your manager/config.json to set the holddown timer to 10 seconds!

Regards
Philip

**Comment by githubfrance** [comment]
Hallo Philipp
Vielen Dank, das war die Lösung
Wenn ich so weit bin dann schicke Ich Dir das Programm
MFG
Patrick
