### ISSUE TITLE
Creating a new Class

### ISSUE THREAD

**Issue by frequencx** [dgray10/SecPi#94]
I'd like to create a new class. So far I have understood the necessity to create a new python script in /opt/secpi/worker/. 

What else is necessary? Where do I define the "Module" name? Does a new class have to be registered in the database?

Thanks for any quick hint!

**Comment by phwoelfel** [comment]
Hey

You just have to create the file in the directory you mentioned and then use it as a Sensor or Action, whatever you are creating.
"Class" is the name of the class you create and "Module" is the name of the file it is in. (More info on Python modules: http://www.tutorialspoint.com/python/python_modules.htm )
The class is then automatically loaded from the worker.

**Comment by frequencx** [comment]
Thanks!
