### ISSUE TITLE
Worker configuration

### ISSUE THREAD

**Issue by drfranky** [dgray10/SecPi#96]
Hello,

I have a issue with worker, I am not sure what IP need to set if I use one raspberry for manager, webinterface and worker.
Could you explain me what IP need to be set if I use only one raspberry?

Thanks in advance

**Comment by drfranky** [comment]
Also after new installation I receive this error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 667, in respond
    self.hooks.run('before_handler')
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 114, in run
    raise exc
IOError: [Errno 2] No such file or directory: '/opt/secpi/webinterface/.htdigest'

I don't know how to fix it.

**Comment by phwoelfel** [comment]
Hey

You have to set it to the IP address of your raspberry pi as you are using it for all three components.

The .htdigest file for the webserver authentication is missing. Did you execute the install.sh script? This should create the htdigest file for you.
The webinterface folder also contains a simple script to generate the file for you. You have to execute it like this:

```
./create_htdigest.sh .htdigest admin password
```

The first parameter is the filename (this has to be .htdigest), the second one is the username and the third one the password.

Hope this helps!
