### ISSUE TITLE
Start / Stop as Action

### ISSUE THREAD

**Issue by blackmamba88** [dgray10/SecPi#98]
Would it be possible to start / stop the service via e.g. a switch on GPIO or NCF etc.

This would be much more comfortable than entering the webinterface and deactivating it

is there a possible way to add code to get this?

**Comment by MartinLiebl** [comment]
We are thinking about a way to open up the activation/deactivation of setups. Issue #73 will be used to track the progress on this topic. I guess we will be able to release this with version 1.1 or 1.2.
